version: "3"
networks:
  nginx:
    external: true
services:
  web:
    image: nginx:alpine
    #ports:
    #  - 8000:80
    networks:
      - nginx
    volumes:
      - ./build/_dist/:/usr/share/nginx/html:ro
      #- ./config/default.conf:/etc/nginx/conf.d/default.conf

